"""render phase and daily budget

Revision ID: 2311b5c5d161
Revises: df9f4dab709f
Create Date: 2026-09-08 13:25:01.380837+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2311b5c5d161"
down_revision: str | None = "df9f4dab709f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "renders",
        sa.Column("phase", sa.String(length=32), server_default="screening", nullable=False),
    )
    op.add_column("renders", sa.Column("daily_budget_usd", sa.Float(), nullable=True))
    op.add_column(
        "renders", sa.Column("scale_started_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("renders", "scale_started_at")
    op.drop_column("renders", "daily_budget_usd")
    op.drop_column("renders", "phase")
    # ### end Alembic commands ###
