"""initial schema

Revision ID: df9f4dab709f
Revises:
Create Date: 2026-09-08 11:14:41.982258+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "df9f4dab709f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("meta_account_id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.String(length=64), nullable=True),
        sa.Column("pixel_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attribution_setting", sa.String(length=32), nullable=False),
        sa.Column("api_version", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("daily_cap_usd", sa.Float(), nullable=True),
        sa.Column("access_token_enc", sa.Text(), nullable=True),
        sa.Column("page_token_enc", sa.Text(), nullable=True),
        sa.Column("is_fake", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_accounts")),
        sa.UniqueConstraint("meta_account_id", name=op.f("uq_ad_accounts_meta_account_id")),
    )
    op.create_index(op.f("ix_ad_accounts_status"), "ad_accounts", ["status"], unique=False)
    op.create_table(
        "archive_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("n_trajectories", sa.Integer(), nullable=False),
        sa.Column("n_tier2", sa.Integer(), nullable=False),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive_snapshots")),
        sa.UniqueConstraint("hash", name=op.f("uq_archive_snapshots_hash")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_log_object_id"), "audit_log", ["object_id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("qualifying_condition", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("contributed_by", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("example_trajectory_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("slug", name=op.f("uq_cards_slug")),
    )
    op.create_index(op.f("ix_cards_kind"), "cards", ["kind"], unique=False)
    op.create_index(op.f("ix_cards_status"), "cards", ["status"], unique=False)
    op.create_table(
        "config_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hash", sa.String(length=16), nullable=False),
        sa.Column("yaml_text", sa.Text(), nullable=False),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied_by", sa.String(length=120), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config_versions")),
        sa.UniqueConstraint("hash", name=op.f("uq_config_versions_hash")),
    )
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("holdout_brief_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("attribution_setting", sa.String(length=32), nullable=True),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_index(op.f("ix_eval_runs_status"), "eval_runs", ["status"], unique=False)
    op.create_table(
        "fake_meta_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fake_meta_objects")),
        sa.UniqueConstraint(
            "kind", "external_id", name=op.f("uq_fake_meta_objects_kind_external_id")
        ),
    )
    op.create_index(
        op.f("ix_fake_meta_objects_account_id"), "fake_meta_objects", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_fake_meta_objects_kind"), "fake_meta_objects", ["kind"], unique=False)
    op.create_table(
        "holdout_campaigns",
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("added_by", sa.String(length=120), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("campaign_id", name=op.f("pk_holdout_campaigns")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("kind", "key", name=op.f("uq_jobs_kind_key")),
    )
    op.create_index(op.f("ix_jobs_kind"), "jobs", ["kind"], unique=False)
    op.create_index(op.f("ix_jobs_scheduled_for"), "jobs", ["scheduled_for"], unique=False)
    op.create_index(op.f("ix_jobs_state"), "jobs", ["state"], unique=False)
    op.create_table(
        "kill_switch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipping_enabled", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=120), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switch")),
    )
    op.create_table(
        "rm_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trained_on_snapshot", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rm_models")),
        sa.UniqueConstraint("version", name=op.f("uq_rm_models_version")),
    )
    op.create_table(
        "training_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("rm_version", sa.String(length=64), nullable=True),
        sa.Column("verifier_version", sa.String(length=64), nullable=True),
        sa.Column("base_model", sa.String(length=128), nullable=True),
        sa.Column("checkpoint_uri", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stop_reason", sa.String(length=255), nullable=True),
        sa.Column("logs_uri", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_runs")),
    )
    op.create_index(op.f("ix_training_runs_status"), "training_runs", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "verifier_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trained_on_labels", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verifier_models")),
        sa.UniqueConstraint("version", name=op.f("uq_verifier_models_version")),
    )
    op.create_table(
        "briefs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ad_account_id", sa.UUID(), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("product", sa.Text(), nullable=False),
        sa.Column("offer", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("goal_metric", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("world_state", sa.Text(), nullable=False),
        sa.Column("world_state_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("constraints", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("brand_assets", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", Vector(384), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_briefs_ad_account_id_ad_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefs")),
    )
    op.create_index(op.f("ix_briefs_ad_account_id"), "briefs", ["ad_account_id"], unique=False)
    op.create_index(op.f("ix_briefs_category"), "briefs", ["category"], unique=False)
    op.create_table(
        "card_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["cards.id"],
            name=op.f("fk_card_relations_from_id_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_id"], ["cards.id"], name=op.f("fk_card_relations_to_id_cards"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_relations")),
        sa.UniqueConstraint(
            "from_id", "to_id", "kind", name=op.f("uq_card_relations_from_id_to_id_kind")
        ),
    )
    op.create_index(op.f("ix_card_relations_from_id"), "card_relations", ["from_id"], unique=False)
    op.create_index(op.f("ix_card_relations_to_id"), "card_relations", ["to_id"], unique=False)
    op.create_table(
        "card_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("qualifying_condition", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("edited_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_versions_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_versions")),
        sa.UniqueConstraint("card_id", "version", name=op.f("uq_card_versions_card_id_version")),
    )
    op.create_index(op.f("ix_card_versions_card_id"), "card_versions", ["card_id"], unique=False)
    op.create_table(
        "combinations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("card_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("niche_key", sa.String(length=512), nullable=False),
        sa.Column("uses", sa.Integer(), nullable=False),
        sa.Column("tier_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tier2_rate", sa.Float(), nullable=True),
        sa.Column("first_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("named_as_card_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["named_as_card_id"],
            ["cards.id"],
            name=op.f("fk_combinations_named_as_card_id_cards"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_combinations")),
        sa.UniqueConstraint("card_ids", name=op.f("uq_combinations_card_ids")),
    )
    op.create_index(op.f("ix_combinations_niche_key"), "combinations", ["niche_key"], unique=False)
    op.create_table(
        "eval_arms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("eval_run_id", sa.UUID(), nullable=False),
        sa.Column("system", sa.String(length=64), nullable=False),
        sa.Column("blind_label", sa.String(length=16), nullable=False),
        sa.Column("n_briefs", sa.Integer(), nullable=False),
        sa.Column("tier2_rate", sa.Float(), nullable=True),
        sa.Column("ci_low", sa.Float(), nullable=True),
        sa.Column("ci_high", sa.Float(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["eval_run_id"],
            ["eval_runs.id"],
            name=op.f("fk_eval_arms_eval_run_id_eval_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_arms")),
    )
    op.create_index(op.f("ix_eval_arms_eval_run_id"), "eval_arms", ["eval_run_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "search_episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("brief_id", sa.UUID(), nullable=False),
        sa.Column("ad_account_id", sa.UUID(), nullable=True),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("budget_cap", sa.Float(), nullable=False),
        sa.Column("spent", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("keep_running_after_outlier", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=True),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stop_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_search_episodes_ad_account_id_ad_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_search_episodes_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_episodes")),
    )
    op.create_index(
        op.f("ix_search_episodes_ad_account_id"), "search_episodes", ["ad_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_episodes_brief_id"), "search_episodes", ["brief_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_episodes_campaign_id"), "search_episodes", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_search_episodes_status"), "search_episodes", ["status"], unique=False)
    op.create_table(
        "batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("prompt_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("state_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["search_episodes.id"],
            name=op.f("fk_batches_episode_id_search_episodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
        sa.UniqueConstraint("episode_id", "index", name=op.f("uq_batches_episode_id_index")),
    )
    op.create_index(op.f("ix_batches_episode_id"), "batches", ["episode_id"], unique=False)
    op.create_index(op.f("ix_batches_state"), "batches", ["state"], unique=False)
    op.create_table(
        "trajectories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("brief_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=True),
        sa.Column("attempt_index", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.String(length=120), nullable=False),
        sa.Column("author_kind", sa.String(length=32), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=True),
        sa.Column("card_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("verified_card_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("tag_source", sa.String(length=32), nullable=True),
        sa.Column("tag_match", sa.Boolean(), nullable=True),
        sa.Column("tag_jaccard", sa.Float(), nullable=True),
        sa.Column("typicality", sa.String(length=16), nullable=True),
        sa.Column("format_ok", sa.Boolean(), nullable=False),
        sa.Column("format_errors", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("cited_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("angle", sa.Text(), nullable=False),
        sa.Column("copy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("visual_brief", sa.Text(), nullable=False),
        sa.Column("preship", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outlier_tier", sa.Integer(), nullable=True),
        sa.Column("outcome_render_id", sa.UUID(), nullable=True),
        sa.Column("outcome_measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rm_score", sa.Float(), nullable=True),
        sa.Column("rm_version", sa.String(length=64), nullable=True),
        sa.Column("library_version", sa.Integer(), nullable=False),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column("combo_angle_embedding", Vector(384), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
            name=op.f("fk_trajectories_batch_id_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["briefs.id"],
            name=op.f("fk_trajectories_brief_id_briefs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["search_episodes.id"],
            name=op.f("fk_trajectories_episode_id_search_episodes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trajectories")),
    )
    op.create_index(op.f("ix_trajectories_batch_id"), "trajectories", ["batch_id"], unique=False)
    op.create_index(op.f("ix_trajectories_brief_id"), "trajectories", ["brief_id"], unique=False)
    op.create_index(
        op.f("ix_trajectories_campaign_id"), "trajectories", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_trajectories_episode_id"), "trajectories", ["episode_id"], unique=False
    )
    op.create_index(
        op.f("ix_trajectories_outlier_tier"), "trajectories", ["outlier_tier"], unique=False
    )
    op.create_index(
        op.f("ix_trajectories_typicality"), "trajectories", ["typicality"], unique=False
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trajectory_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.String(length=120), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trajectory_id"],
            ["trajectories.id"],
            name=op.f("fk_notes_trajectory_id_trajectories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(op.f("ix_notes_trajectory_id"), "notes", ["trajectory_id"], unique=False)
    op.create_table(
        "renders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trajectory_id", sa.UUID(), nullable=False),
        sa.Column("image_uri", sa.Text(), nullable=True),
        sa.Column("image_backend", sa.String(length=32), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("meta_ad_id", sa.String(length=64), nullable=True),
        sa.Column("meta_adset_id", sa.String(length=64), nullable=True),
        sa.Column("meta_creative_id", sa.String(length=64), nullable=True),
        sa.Column("effective_object_story_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trajectory_id"],
            ["trajectories.id"],
            name=op.f("fk_renders_trajectory_id_trajectories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_renders")),
    )
    op.create_index(op.f("ix_renders_meta_ad_id"), "renders", ["meta_ad_id"], unique=False)
    op.create_index(op.f("ix_renders_status"), "renders", ["status"], unique=False)
    op.create_index(op.f("ix_renders_trajectory_id"), "renders", ["trajectory_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trajectory_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("corrected_card_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("reviewer_id", sa.String(length=120), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trajectory_id"],
            ["trajectories.id"],
            name=op.f("fk_reviews_trajectory_id_trajectories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("trajectory_id", name=op.f("uq_reviews_trajectory_id")),
    )
    op.create_index(op.f("ix_reviews_label"), "reviews", ["label"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("render_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("commenter_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("filtered_reason", sa.String(length=64), nullable=True),
        sa.Column("pii_removed", sa.Boolean(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["render_id"],
            ["renders.id"],
            name=op.f("fk_comments_render_id_renders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        sa.UniqueConstraint("external_id", name=op.f("uq_comments_external_id")),
    )
    op.create_index(op.f("ix_comments_render_id"), "comments", ["render_id"], unique=False)
    op.create_table(
        "daily_insights",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("render_id", sa.UUID(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("link_clicks", sa.Integer(), nullable=False),
        sa.Column("spend", sa.Float(), nullable=False),
        sa.Column("purchases", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("reactions", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("saves", sa.Integer(), nullable=False),
        sa.Column("daily_budget", sa.Float(), nullable=True),
        sa.Column("attribution_setting", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["render_id"],
            ["renders.id"],
            name=op.f("fk_daily_insights_render_id_renders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_insights")),
        sa.UniqueConstraint("render_id", "day", name=op.f("uq_daily_insights_render_id_day")),
    )
    op.create_index(op.f("ix_daily_insights_day"), "daily_insights", ["day"], unique=False)
    op.create_index(
        op.f("ix_daily_insights_render_id"), "daily_insights", ["render_id"], unique=False
    )
    op.create_table(
        "outcomes",
        sa.Column("render_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("conversions", sa.Integer(), nullable=False),
        sa.Column("spend", sa.Float(), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=False),
        sa.Column("days_at_scale", sa.Integer(), nullable=False),
        sa.Column("account_median_90d", sa.Float(), nullable=False),
        sa.Column("account_median_human_90d", sa.Float(), nullable=True),
        sa.Column("category_median", sa.Float(), nullable=False),
        sa.Column("baseline", sa.String(length=32), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=False),
        sa.Column("ratio_lower_bound", sa.Float(), nullable=False),
        sa.Column("outlier_tier", sa.Integer(), nullable=False),
        sa.Column("gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attribution_setting", sa.String(length=32), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["render_id"],
            ["renders.id"],
            name=op.f("fk_outcomes_render_id_renders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("render_id", name=op.f("pk_outcomes")),
    )
    op.create_index(op.f("ix_outcomes_outlier_tier"), "outcomes", ["outlier_tier"], unique=False)
    op.create_table(
        "screening_stats",
        sa.Column("render_id", sa.UUID(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("link_clicks", sa.Integer(), nullable=False),
        sa.Column("spend", sa.Float(), nullable=False),
        sa.Column("ctr", sa.Float(), nullable=False),
        sa.Column("cpc", sa.Float(), nullable=True),
        sa.Column("ctr_lower_bound", sa.Float(), nullable=False),
        sa.Column("account_median_ctr_90d", sa.Float(), nullable=False),
        sa.Column("screening_ratio", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("window_complete", sa.Boolean(), nullable=False),
        sa.Column("engagement", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["render_id"],
            ["renders.id"],
            name=op.f("fk_screening_stats_render_id_renders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("render_id", name=op.f("pk_screening_stats")),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trajectory_id", sa.UUID(), nullable=False),
        sa.Column("render_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sentiment", sa.String(length=32), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("extracted_by", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("decided_by", sa.String(length=120), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["render_id"],
            ["renders.id"],
            name=op.f("fk_signals_render_id_renders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trajectory_id"],
            ["trajectories.id"],
            name=op.f("fk_signals_trajectory_id_trajectories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(op.f("ix_signals_kind"), "signals", ["kind"], unique=False)
    op.create_index(op.f("ix_signals_render_id"), "signals", ["render_id"], unique=False)
    op.create_index(op.f("ix_signals_status"), "signals", ["status"], unique=False)
    op.create_index(op.f("ix_signals_trajectory_id"), "signals", ["trajectory_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_trajectory_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_status"), table_name="signals")
    op.drop_index(op.f("ix_signals_render_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_kind"), table_name="signals")
    op.drop_table("signals")
    op.drop_table("screening_stats")
    op.drop_index(op.f("ix_outcomes_outlier_tier"), table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index(op.f("ix_daily_insights_render_id"), table_name="daily_insights")
    op.drop_index(op.f("ix_daily_insights_day"), table_name="daily_insights")
    op.drop_table("daily_insights")
    op.drop_index(op.f("ix_comments_render_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_reviews_label"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_renders_trajectory_id"), table_name="renders")
    op.drop_index(op.f("ix_renders_status"), table_name="renders")
    op.drop_index(op.f("ix_renders_meta_ad_id"), table_name="renders")
    op.drop_table("renders")
    op.drop_index(op.f("ix_notes_trajectory_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_trajectories_typicality"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_outlier_tier"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_episode_id"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_campaign_id"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_brief_id"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_batch_id"), table_name="trajectories")
    op.drop_table("trajectories")
    op.drop_index(op.f("ix_batches_state"), table_name="batches")
    op.drop_index(op.f("ix_batches_episode_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_search_episodes_status"), table_name="search_episodes")
    op.drop_index(op.f("ix_search_episodes_campaign_id"), table_name="search_episodes")
    op.drop_index(op.f("ix_search_episodes_brief_id"), table_name="search_episodes")
    op.drop_index(op.f("ix_search_episodes_ad_account_id"), table_name="search_episodes")
    op.drop_table("search_episodes")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_eval_arms_eval_run_id"), table_name="eval_arms")
    op.drop_table("eval_arms")
    op.drop_index(op.f("ix_combinations_niche_key"), table_name="combinations")
    op.drop_table("combinations")
    op.drop_index(op.f("ix_card_versions_card_id"), table_name="card_versions")
    op.drop_table("card_versions")
    op.drop_index(op.f("ix_card_relations_to_id"), table_name="card_relations")
    op.drop_index(op.f("ix_card_relations_from_id"), table_name="card_relations")
    op.drop_table("card_relations")
    op.drop_index(op.f("ix_briefs_category"), table_name="briefs")
    op.drop_index(op.f("ix_briefs_ad_account_id"), table_name="briefs")
    op.drop_table("briefs")
    op.drop_table("verifier_models")
    op.drop_table("users")
    op.drop_index(op.f("ix_training_runs_status"), table_name="training_runs")
    op.drop_table("training_runs")
    op.drop_table("rm_models")
    op.drop_table("kill_switch")
    op.drop_index(op.f("ix_jobs_state"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_scheduled_for"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_kind"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("holdout_campaigns")
    op.drop_index(op.f("ix_fake_meta_objects_kind"), table_name="fake_meta_objects")
    op.drop_index(op.f("ix_fake_meta_objects_account_id"), table_name="fake_meta_objects")
    op.drop_table("fake_meta_objects")
    op.drop_index(op.f("ix_eval_runs_status"), table_name="eval_runs")
    op.drop_table("eval_runs")
    op.drop_table("config_versions")
    op.drop_index(op.f("ix_cards_status"), table_name="cards")
    op.drop_index(op.f("ix_cards_kind"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_audit_log_object_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("archive_snapshots")
    op.drop_index(op.f("ix_ad_accounts_status"), table_name="ad_accounts")
    op.drop_table("ad_accounts")
    # ### end Alembic commands ###
